name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main  # Runs when you push to the main branch
      
jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            himanshudevx/todo:latest
            himanshudevx/todo:${{ github.sha }}
          cache-from: type=registry,ref=himanshudevx/todo:latest
          cache-to: type=inline

      - name: Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "himanshudevx/todo:latest"
          exit-code: 0 # Warns but doesn't fail the build
